package dk.bitmovers.timeregistration.model;

// Generated Jun 1, 2015 4:47:34 AM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * RegistrationSubmitted generated by hbm2java
 */
@Entity
@Table(name = "registration_submitted", catalog = "timereg")
public class RegistrationSubmitted implements java.io.Serializable {

	private Integer id;
	private RegistrationItem registrationItem;
	private User user;
	private Date created;
	private BigDecimal amount;
	private String comments;

	public RegistrationSubmitted() {
	}

	public RegistrationSubmitted(RegistrationItem registrationItem, User user,
			Date created, BigDecimal amount) {
		this.registrationItem = registrationItem;
		this.user = user;
		this.created = created;
		this.amount = amount;
	}

	public RegistrationSubmitted(RegistrationItem registrationItem, User user,
			Date created, BigDecimal amount, String comments) {
		this.registrationItem = registrationItem;
		this.user = user;
		this.created = created;
		this.amount = amount;
		this.comments = comments;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "registration_item_id", nullable = false)
	public RegistrationItem getRegistrationItem() {
		return this.registrationItem;
	}

	public void setRegistrationItem(RegistrationItem registrationItem) {
		this.registrationItem = registrationItem;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "amount", nullable = false, precision = 5, scale = 1)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Column(name = "comments", length = 120)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
