package dk.bitmovers.timeregistration.model;

// Generated Jun 1, 2015 5:56:38 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "timereg")
public class User implements java.io.Serializable {

	private Integer id;
	private Date created;
	private String login;
	private String name;
	private String locale;
	private String language;
	private String isLoginEnabled;
	private byte enabled;
	private Set<RegistrationSubmitted> registrationSubmitteds = new HashSet<RegistrationSubmitted>(
			0);
	private Set<Client> clients = new HashSet<Client>(0);
	private Set<ProviderAccount> providerAccounts = new HashSet<ProviderAccount>(
			0);
	private Set<WorkClockEvent> workClockEvents = new HashSet<WorkClockEvent>(0);
	private Set<Provider> providers = new HashSet<Provider>(0);
	private Set<RegistrationEvent> registrationEvents = new HashSet<RegistrationEvent>(
			0);
	private Set<RegistrationItem> registrationItems = new HashSet<RegistrationItem>(
			0);
	private Set<UserRoleLink> userRoleLinks = new HashSet<UserRoleLink>(0);
	private Set<UserPassword> userPasswords = new HashSet<UserPassword>(0);
	private Set<ClientProject> clientProjects = new HashSet<ClientProject>(0);

	public User() {
	}

	public User(Date created, String login, String isLoginEnabled, byte enabled, String locale,String language) {
		this.created = created;
		this.login = login;
		this.isLoginEnabled = isLoginEnabled;
		this.enabled = enabled;
		this.locale = locale;
		this.language = language;
	}

	public User(Date created, String login, String name, String isLoginEnabled,
			byte enabled, String locale,String language, Set<RegistrationSubmitted> registrationSubmitteds,
			Set<Client> clients, Set<ProviderAccount> providerAccounts,
			Set<WorkClockEvent> workClockEvents, Set<Provider> providers,
			Set<RegistrationEvent> registrationEvents,
			Set<RegistrationItem> registrationItems,
			Set<UserRoleLink> userRoleLinks, Set<UserPassword> userPasswords,
			Set<ClientProject> clientProjects) {
		this.created = created;
		this.login = login;
		this.name = name;
		this.isLoginEnabled = isLoginEnabled;
		this.enabled = enabled;
		this.registrationSubmitteds = registrationSubmitteds;
		this.clients = clients;
		this.providerAccounts = providerAccounts;
		this.workClockEvents = workClockEvents;
		this.providers = providers;
		this.registrationEvents = registrationEvents;
		this.registrationItems = registrationItems;
		this.userRoleLinks = userRoleLinks;
		this.userPasswords = userPasswords;
		this.clientProjects = clientProjects;
		this.locale = locale;
		this.language = language;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "login", nullable = false, length = 80)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "name", length = 140)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "is_login_enabled", nullable = false, length = 2)
	public String getIsLoginEnabled() {
		return this.isLoginEnabled;
	}

	public void setIsLoginEnabled(String isLoginEnabled) {
		this.isLoginEnabled = isLoginEnabled;
	}

	@Column(name = "enabled", nullable = false)
	public byte getEnabled() {
		return this.enabled;
	}

	public void setEnabled(byte enabled) {
		this.enabled = enabled;
	}
	
	@Column(name = "locale", nullable = true, length = 3)
	public String getLocale() {
		return this.locale;
	}

	public void setLocale(String login) {
		this.locale = login;
	}
	
	@Column(name = "language", nullable = true, length = 3)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String login) {
		this.language = login;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<RegistrationSubmitted> getRegistrationSubmitteds() {
		return this.registrationSubmitteds;
	}

	public void setRegistrationSubmitteds(
			Set<RegistrationSubmitted> registrationSubmitteds) {
		this.registrationSubmitteds = registrationSubmitteds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Client> getClients() {
		return this.clients;
	}

	public void setClients(Set<Client> clients) {
		this.clients = clients;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<ProviderAccount> getProviderAccounts() {
		return this.providerAccounts;
	}

	public void setProviderAccounts(Set<ProviderAccount> providerAccounts) {
		this.providerAccounts = providerAccounts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<WorkClockEvent> getWorkClockEvents() {
		return this.workClockEvents;
	}

	public void setWorkClockEvents(Set<WorkClockEvent> workClockEvents) {
		this.workClockEvents = workClockEvents;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<Provider> getProviders() {
		return this.providers;
	}

	public void setProviders(Set<Provider> providers) {
		this.providers = providers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<RegistrationEvent> getRegistrationEvents() {
		return this.registrationEvents;
	}

	public void setRegistrationEvents(Set<RegistrationEvent> registrationEvents) {
		this.registrationEvents = registrationEvents;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<RegistrationItem> getRegistrationItems() {
		return this.registrationItems;
	}

	public void setRegistrationItems(Set<RegistrationItem> registrationItems) {
		this.registrationItems = registrationItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<UserRoleLink> getUserRoleLinks() {
		return this.userRoleLinks;
	}

	public void setUserRoleLinks(Set<UserRoleLink> userRoleLinks) {
		this.userRoleLinks = userRoleLinks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<UserPassword> getUserPasswords() {
		return this.userPasswords;
	}

	public void setUserPasswords(Set<UserPassword> userPasswords) {
		this.userPasswords = userPasswords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set<ClientProject> getClientProjects() {
		return this.clientProjects;
	}

	public void setClientProjects(Set<ClientProject> clientProjects) {
		this.clientProjects = clientProjects;
	}

}
