package dk.bitmovers.timeregistration.model;

// Generated Jun 1, 2015 4:50:21 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * ClientProject generated by hbm2java
 */
@Entity
@Table(name = "client_project", catalog = "timereg", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class ClientProject implements java.io.Serializable {

	private Integer id;
	private Client client;
	private User user;
	private Date created;
	private String code;
	private String name;
	private String isActive;
	private Set registrationItems = new HashSet(0);

	public ClientProject() {
	}

	public ClientProject(Client client, User user, Date created, String code,
			String name, String isActive) {
		this.client = client;
		this.user = user;
		this.created = created;
		this.code = code;
		this.name = name;
		this.isActive = isActive;
	}

	public ClientProject(Client client, User user, Date created, String code,
			String name, String isActive, Set registrationItems) {
		this.client = client;
		this.user = user;
		this.created = created;
		this.code = code;
		this.name = name;
		this.isActive = isActive;
		this.registrationItems = registrationItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "client_id", nullable = false)
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "code", unique = true, nullable = false, length = 20)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "is_active", nullable = false, length = 2)
	public String getIsActive() {
		return this.isActive;
	}

	public void setIsActive(String isActive) {
		this.isActive = isActive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clientProject")
	public Set getRegistrationItems() {
		return this.registrationItems;
	}

	public void setRegistrationItems(Set registrationItems) {
		this.registrationItems = registrationItems;
	}

}
