package dk.bitmovers.timeregistration.model;

// Generated Jun 1, 2015 4:50:21 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "timereg")
public class Role implements java.io.Serializable {

	private Integer id;
	private Date created;
	private String role;
	private Set userRoleLinks = new HashSet(0);

	public Role() {
	}

	public Role(Date created, String role) {
		this.created = created;
		this.role = role;
	}

	public Role(Date created, String role, Set userRoleLinks) {
		this.created = created;
		this.role = role;
		this.userRoleLinks = userRoleLinks;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "role", nullable = false, length = 60)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set getUserRoleLinks() {
		return this.userRoleLinks;
	}

	public void setUserRoleLinks(Set userRoleLinks) {
		this.userRoleLinks = userRoleLinks;
	}

}
