package dk.bitmovers.timeregistration.model;

// Generated Jun 1, 2015 4:50:21 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "timereg")
public class User implements java.io.Serializable {

	private Integer id;
	private Date created;
	private String login;
	private String name;
	private String isLoginEnabled;
	private byte enabled;
	private Set registrationSubmitteds = new HashSet(0);
	private Set clients = new HashSet(0);
	private Set providerAccounts = new HashSet(0);
	private Set workClockEvents = new HashSet(0);
	private Set providers = new HashSet(0);
	private Set registrationEvents = new HashSet(0);
	private Set registrationItems = new HashSet(0);
	private Set userRoleLinks = new HashSet(0);
	private Set userPasswords = new HashSet(0);
	private Set clientProjects = new HashSet(0);

	public User() {
	}

	public User(Date created, String login, String isLoginEnabled, byte enabled) {
		this.created = created;
		this.login = login;
		this.isLoginEnabled = isLoginEnabled;
		this.enabled = enabled;
	}

	public User(Date created, String login, String name, String isLoginEnabled,
			byte enabled, Set registrationSubmitteds, Set clients,
			Set providerAccounts, Set workClockEvents, Set providers,
			Set registrationEvents, Set registrationItems, Set userRoleLinks,
			Set userPasswords, Set clientProjects) {
		this.created = created;
		this.login = login;
		this.name = name;
		this.isLoginEnabled = isLoginEnabled;
		this.enabled = enabled;
		this.registrationSubmitteds = registrationSubmitteds;
		this.clients = clients;
		this.providerAccounts = providerAccounts;
		this.workClockEvents = workClockEvents;
		this.providers = providers;
		this.registrationEvents = registrationEvents;
		this.registrationItems = registrationItems;
		this.userRoleLinks = userRoleLinks;
		this.userPasswords = userPasswords;
		this.clientProjects = clientProjects;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "login", nullable = false, length = 80)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "name", length = 140)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "is_login_enabled", nullable = false, length = 2)
	public String getIsLoginEnabled() {
		return this.isLoginEnabled;
	}

	public void setIsLoginEnabled(String isLoginEnabled) {
		this.isLoginEnabled = isLoginEnabled;
	}

	@Column(name = "enabled", nullable = false)
	public byte getEnabled() {
		return this.enabled;
	}

	public void setEnabled(byte enabled) {
		this.enabled = enabled;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set getRegistrationSubmitteds() {
		return this.registrationSubmitteds;
	}

	public void setRegistrationSubmitteds(Set registrationSubmitteds) {
		this.registrationSubmitteds = registrationSubmitteds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set getClients() {
		return this.clients;
	}

	public void setClients(Set clients) {
		this.clients = clients;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set getProviderAccounts() {
		return this.providerAccounts;
	}

	public void setProviderAccounts(Set providerAccounts) {
		this.providerAccounts = providerAccounts;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set getWorkClockEvents() {
		return this.workClockEvents;
	}

	public void setWorkClockEvents(Set workClockEvents) {
		this.workClockEvents = workClockEvents;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set getProviders() {
		return this.providers;
	}

	public void setProviders(Set providers) {
		this.providers = providers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set getRegistrationEvents() {
		return this.registrationEvents;
	}

	public void setRegistrationEvents(Set registrationEvents) {
		this.registrationEvents = registrationEvents;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set getRegistrationItems() {
		return this.registrationItems;
	}

	public void setRegistrationItems(Set registrationItems) {
		this.registrationItems = registrationItems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set getUserRoleLinks() {
		return this.userRoleLinks;
	}

	public void setUserRoleLinks(Set userRoleLinks) {
		this.userRoleLinks = userRoleLinks;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set getUserPasswords() {
		return this.userPasswords;
	}

	public void setUserPasswords(Set userPasswords) {
		this.userPasswords = userPasswords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "user")
	public Set getClientProjects() {
		return this.clientProjects;
	}

	public void setClientProjects(Set clientProjects) {
		this.clientProjects = clientProjects;
	}

}
