package dk.bitmovers.timeregistration.model;

// Generated Jun 1, 2015 4:50:21 AM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkClockEventType generated by hbm2java
 */
@Entity
@Table(name = "work_clock_event_type", catalog = "timereg")
public class WorkClockEventType implements java.io.Serializable {

	private Integer id;
	private Date created;
	private String eventType;
	private Set workClockEvents = new HashSet(0);

	public WorkClockEventType() {
	}

	public WorkClockEventType(Date created, String eventType) {
		this.created = created;
		this.eventType = eventType;
	}

	public WorkClockEventType(Date created, String eventType,
			Set workClockEvents) {
		this.created = created;
		this.eventType = eventType;
		this.workClockEvents = workClockEvents;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created", nullable = false, length = 19)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	@Column(name = "event_type", nullable = false, length = 60)
	public String getEventType() {
		return this.eventType;
	}

	public void setEventType(String eventType) {
		this.eventType = eventType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workClockEventType")
	public Set getWorkClockEvents() {
		return this.workClockEvents;
	}

	public void setWorkClockEvents(Set workClockEvents) {
		this.workClockEvents = workClockEvents;
	}

}
